server:
  port: 8888
spring:
  application:
    name: config
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Abigale84/spring-cloud-sample.git #配置git仓库地址
          searchPaths: spring-cloud-sample/config #配置仓库路径
          username: qliu_lq@163.com #访问git仓库的用户名
          password: qiong082519 #访问git仓库的用户密码
      label: development #配置仓库的分支
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/